import * as THREE from 'three';
const canvas=document.querySelector('#world'),renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x101820);scene.fog=new THREE.Fog(0x101820,18,42);
const camera=new THREE.PerspectiveCamera(55,1,.1,80);scene.add(new THREE.HemisphereLight(0x9bc5df,0x24180f,2));const lamp=new THREE.PointLight(0xffbd65,35,18);scene.add(lamp);
const M=c=>new THREE.MeshStandardMaterial({color:c,roughness:.8}),rockM=M(0x59463a),dirtM=M(0x76543d),oreM=M(0x43c6d9),skin=M(0xefb17f),yellow=M(0xe7a32b),shirt=M(0xe5ddc6),denim=M(0x476d7d),black=M(0x111111),white=M(0xffffff);
function mesh(g,m,p=scene){const x=new THREE.Mesh(g,m);x.castShadow=x.receiveShadow=true;p.add(x);return x}
const floor=mesh(new THREE.PlaneGeometry(50,200),dirtM);floor.rotation.x=-Math.PI/2;floor.position.set(0,-1,-75);
for(let z=3;z>-145;z-=4)for(const x of [-8,-6,6,8]){const b=mesh(new THREE.BoxGeometry(2.1,4,3.8),rockM);b.position.set(x,1,z+(Math.random()-.5));b.rotation.y=(Math.random()-.5)*.25}
const rocks=[];for(let z=-8;z>-145;z-=5){for(let i=0;i<3;i++){const ore=Math.random()<.24,r=mesh(new THREE.DodecahedronGeometry(.7+Math.random()*.45,1),ore?oreM:rockM);r.position.set((Math.random()-.5)*9,-.25,z+(Math.random()-.5)*2);r.userData={ore,hp:ore?3:2};rocks.push(r)}}
const dave=new THREE.Group();scene.add(dave);const body=mesh(new THREE.BoxGeometry(.9,1.1,.6),shirt,dave);body.position.y=.9;const head=mesh(new THREE.SphereGeometry(.55,16,12),skin,dave);head.position.y=1.8;const brim=mesh(new THREE.CylinderGeometry(.65,.65,.08,16),yellow,dave);brim.position.y=2.22;const hat=mesh(new THREE.SphereGeometry(.48,16,8,0,6.28,0,1.57),yellow,dave);hat.position.y=2.24;
for(const s of [-1,1]){const e=mesh(new THREE.SphereGeometry(.16,10,8),white,dave);e.position.set(s*.23,1.9,-.47);const p=mesh(new THREE.SphereGeometry(.07,8,6),black,dave);p.position.set(s*.23,1.9,-.59)}
const pick=new THREE.Group();dave.add(pick);pick.position.set(.55,1,0);const handle=mesh(new THREE.CylinderGeometry(.04,.04,1.7,8),M(0x684027),pick);handle.rotation.z=-.7;const blade=mesh(new THREE.BoxGeometry(.65,.15,.12),M(0x9ba3a5),pick);blade.position.set(.58,-.55,0);blade.rotation.z=-.7;
let state={cash:0,ore:0,cap:12,power:1,depth:0};const keys={};addEventListener('keydown',e=>keys[e.code]=true);addEventListener('keyup',e=>keys[e.code]=false);
let msgT;function msg(t){const el=document.querySelector('#message');el.textContent=t;el.classList.add('show');clearTimeout(msgT);msgT=setTimeout(()=>el.classList.remove('show'),700)}
const pc=()=>15*Math.pow(2,state.power-1),bc=()=>25*Math.pow(2,(state.cap-12)/8);
function ui(){depth.textContent=Math.floor(state.depth)+'m';ore.textContent=state.ore+' / '+state.cap;cash.textContent='$'+Math.floor(state.cash);sellv.textContent='+$'+state.ore*5;powerc.textContent='$'+pc();bagc.textContent='$'+bc();power.disabled=state.cash<pc();bag.disabled=state.cash<bc();shop.classList.toggle('show',dave.position.z>-4)}
sell.onclick=()=>{state.cash+=state.ore*5;state.ore=0;msg('SOLD. DAVE UNDERSTANDS MONEY.')};power.onclick=()=>{if(state.cash>=pc()){state.cash-=pc();state.power++;msg('PICKAXE STRONGER. DAVE SAME.')}};bag.onclick=()=>{if(state.cash>=bc()){state.cash-=bc();state.cap+=8;msg('MORE POCKET.')}};
function hitRock(){if(state.ore>=state.cap){msg('BAG FULL. GO UP.');return}let best=null,dist=2.3;for(const r of rocks){if(!r.parent)continue;const d=r.position.distanceTo(dave.position);if(d<dist){best=r;dist=d}}if(best){best.userData.hp-=state.power;best.scale.multiplyScalar(.88);if(best.userData.hp<=0){if(best.userData.ore){state.ore++;msg('+1 BLUE ROCK')}scene.remove(best)}}}
let last=performance.now(),swing=0;
function loop(now){requestAnimationFrame(loop);const dt=Math.min((now-last)/1000,.04);last=now;const sp=5*dt;if(keys.KeyA)dave.position.x-=sp;if(keys.KeyD)dave.position.x+=sp;if(keys.KeyW)dave.position.z-=sp;if(keys.KeyS)dave.position.z+=sp;dave.position.x=Math.max(-5,Math.min(5,dave.position.x));dave.position.z=Math.max(-142,Math.min(3,dave.position.z));state.depth=Math.max(state.depth,-dave.position.z);if(keys.Space){swing+=dt*12;pick.rotation.x=Math.sin(swing)*1.1;if(Math.sin(swing)>.94&&pick.userData.ready!==false){pick.userData.ready=false;hitRock()}if(Math.sin(swing)<0)pick.userData.ready=true}else pick.rotation.x*=.8;
camera.position.lerp(new THREE.Vector3(dave.position.x*0.35+7,7,dave.position.z+10),.08);camera.lookAt(dave.position.x,0,dave.position.z-3);lamp.position.set(dave.position.x,5,dave.position.z+1);renderer.render(scene,camera);ui()}
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();requestAnimationFrame(loop);